plugins:
  - jekyll-feed
  - jekyll-seo-tag
author:
  name: Jill Lara
  email: yellowbowlo9@gmail.com
theme:
  primary_color: "#ff006e"
  background: "#111"
  secondary_bg: "#222"
  container_bg: "#1a1a1a"
  text_color: "#ddd"
  muted_text: "#999"
  border_color: "#444"
markdown: kramdown
url: https://yellowbowlo9.github.io
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: journal
    values:
      layout: post
  - scope:
      path: ""
      type: poetry
    values:
      layout: post
collections:
  journal:
    output: true
    permalink: /journal/:title/
  poetry:
    output: true
    permalink: /poetry/:title/
  pages:
    output: true
    permalink: /:path/
title: Jill's Blog
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .bundle
  - .git
  - .github
description: Who Did This??
baseurl: ""
